const tasks = [
  {
    id: 0,
    projectId: 2,
    name: "Develop login feature",
    deadline: "2025-03-01",
    description: "Implement user authentication with email and password.",
    assignedPeople: ["Alice", "Bob"],
  },
  {
    id: 1,
    projectId: 1,
    name: "Design dashboard UI",
    deadline: "2025-03-05",
    description: "Create a user-friendly interface for the dashboard.",
    assignedPeople: ["Charlie", "Dave"],
  },
  {
    id: 2,
    projectId: 1,
    name: "Database schema setup",
    deadline: "2025-02-28",
    description: "Define tables and relationships for the database.",
    assignedPeople: ["Eve"],
  },
  {
    projectId: 1,
    id: 3,
    name: "API development for tasks",
    deadline: "2025-03-10",
    description: "Build REST APIs to manage tasks in the system.",
    assignedPeople: ["Frank", "Grace"],
  },
  {
    projectId: 3,
    id: 4,
    name: "User registration feature",
    deadline: "2025-03-03",
    description: "Develop a registration system with email verification.",
    assignedPeople: ["Hank"],
  },
  {
    projectId: 2,
    id: 5,
    name: "Implement task assignment",
    deadline: "2025-03-07",
    description: "Allow team leads to assign tasks to members.",
    assignedPeople: ["Ivy", "Jack"],
  },
  {
    projectId: 1,
    id: 6,
    name: "Optimize database queries",
    deadline: "2025-03-15",
    description: "Improve query performance for faster data retrieval.",
    assignedPeople: ["Kevin"],
  },
  {
    projectId: 1,
    id: 7,
    name: "Write unit tests",
    deadline: "2025-03-12",
    description: "Ensure core functionalities work as expected.",
    assignedPeople: ["Laura", "Mike"],
  },
  {
    projectId: 3,
    id: 8,
    name: "Deploy application",
    deadline: "2025-03-20",
    description: "Deploy the system to a cloud environment.",
    assignedPeople: ["Nancy"],
  },
  {
    projectId: 2,
    id: 9,
    name: "AI-based task estimation",
    deadline: "2025-03-25",
    description: "Implement an AI model to estimate task difficulty.",
    assignedPeople: ["Oscar", "Paul"],
  },
];
const projects = [
  {
    id: 1,
    name: "AI-Based Task Management System",
    members: ["Alice", "Bob", "Charlie", "Dave"],
    manager: "Eve",
  },
  {
    id: 2,
    name: "E-Commerce Platform",
    members: ["Frank", "Grace", "Hank", "Ivy"],
    manager: "Jack",
  },
  {
    id: 3,
    name: "Mobile Banking App",
    members: ["Kevin", "Laura", "Mike", "Nancy"],
    manager: "Oscar",
  },
];

export { tasks, projects };
