# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/Rares
Accept: application/json


###


POST http://127.0.0.1:8000/api/v1/tasks/predict_batch
Content-Type: application/json

[
  {
    "task_id":1,
    "duration": 8,
    "priority": "MEDIUM",
    "subtasks": 1,
    "deadline_days": 7,
    "created_to_deadline": 11,
    "user_past_completion": 0.78,
    "task_type": "documentation",
    "description_length": 135,
    "comments_count": 3,
    "assigned_team_size": 2,
    "user_availability": 71,
    "no_curr_asigned_tasks": 1,
    "tasks_completed": 33,
    "overdue_tasks": 3,
    "avg_completion_time": 0.1,
    "completed_on_time": 1
  },
  {
    "task_id":1,
    "duration": 6,
    "priority": "LOW",
    "subtasks": 3,
    "deadline_days": 3,
    "created_to_deadline": 4,
    "user_past_completion": 0.81,
    "task_type": "bug",
    "description_length": 86,
    "comments_count": 3,
    "assigned_team_size": 3,
    "user_availability": 73,
    "no_curr_asigned_tasks": 3,
    "tasks_completed": 30,
    "overdue_tasks": 0,
    "avg_completion_time": 0.14,
    "completed_on_time": 1
  },
  {
    "task_id":1,
    "duration": 8,
    "priority": "LOW",
    "subtasks": 2,
    "deadline_days": 23,
    "created_to_deadline": 28,
    "user_past_completion": 0.93,
    "task_type": "feature",
    "description_length": 131,
    "comments_count": 6,
    "assigned_team_size": 4,
    "user_availability": 72,
    "no_curr_asigned_tasks": 3,
    "tasks_completed": 31,
    "overdue_tasks": 1,
    "avg_completion_time": 0.1,
    "completed_on_time": 1
  },
  {
    "task_id":1,
    "duration": 11,
    "priority": "LOW",
    "subtasks": 3,
    "deadline_days": 18,
    "created_to_deadline": 21,
    "user_past_completion": 0.75,
    "task_type": "bug",
    "description_length": 139,
    "comments_count": 2,
    "assigned_team_size": 2,
    "user_availability": 65,
    "no_curr_asigned_tasks": 6,
    "tasks_completed": 25,
    "overdue_tasks": 5,
    "avg_completion_time": 0.1,
    "completed_on_time": 1
  },
  {
    "task_id":1,
    "duration": 6,
    "priority": "MEDIUM",
    "subtasks": 1,
    "deadline_days": 21,
    "created_to_deadline": 24,
    "user_past_completion": 0.83,
    "task_type": "bug",
    "description_length": 100,
    "comments_count": 3,
    "assigned_team_size": 1,
    "user_availability": 48,
    "no_curr_asigned_tasks": 3,
    "tasks_completed": 59,
    "overdue_tasks": 1,
    "avg_completion_time": 0.13,
    "completed_on_time": 0
  },
  {
    "task_id":1,
    "duration": 6,
    "priority": "LOW",
    "subtasks": 1,
    "deadline_days": 20,
    "created_to_deadline": 22,
    "user_past_completion": 0.84,
    "task_type": "feature",
    "description_length": 104,
    "comments_count": 3,
    "assigned_team_size": 1,
    "user_availability": 64,
    "no_curr_asigned_tasks": 5,
    "tasks_completed": 14,
    "overdue_tasks": 1,
    "avg_completion_time": 0.44,
    "completed_on_time": 1
  },
  {
    "task_id":1,
    "duration": 11,
    "priority": "MEDIUM",
    "subtasks": 2,
    "deadline_days": 13,
    "created_to_deadline": 13,
    "user_past_completion": 0.96,
    "task_type": "bug",
    "description_length": 78,
    "comments_count": 2,
    "assigned_team_size": 2,
    "user_availability": 31,
    "no_curr_asigned_tasks": 2,
    "tasks_completed": 36,
    "overdue_tasks": 4,
    "avg_completion_time": 0.31,
    "completed_on_time": 0
  },
  {
    "task_id":1,
    "duration": 9,
    "priority": "MEDIUM",
    "subtasks": 1,
    "deadline_days": 14,
    "created_to_deadline": 22,
    "user_past_completion": 0.88,
    "task_type": "feature",
    "description_length": 126,
    "comments_count": 3,
    "assigned_team_size": 2,
    "user_availability": 72,
    "no_curr_asigned_tasks": 1,
    "tasks_completed": 17,
    "overdue_tasks": 3,
    "avg_completion_time": 0.45,
    "completed_on_time": 1
  },
  {
    "task_id":1,
    "duration": 5,
    "priority": "LOW",
    "subtasks": 5,
    "deadline_days": 22,
    "created_to_deadline": 27,
    "user_past_completion": 0.79,
    "task_type": "bug",
    "description_length": 95,
    "comments_count": 3,
    "assigned_team_size": 2,
    "user_availability": 58,
    "no_curr_asigned_tasks": 1,
    "tasks_completed": 18,
    "overdue_tasks": 4,
    "avg_completion_time": 0.2,
    "completed_on_time": 1
  },
  {
    "task_id":1,
    "duration": 8,
    "priority": "MEDIUM",
    "subtasks": 3,
    "deadline_days": 26,
    "created_to_deadline": 35,
    "user_past_completion": 0.86,
    "task_type": "feature",
    "description_length": 44,
    "comments_count": 3,
    "assigned_team_size": 2,
    "user_availability": 33,
    "no_curr_asigned_tasks": 2,
    "tasks_completed": 33,
    "overdue_tasks": 1,
    "avg_completion_time": 0.92,
    "completed_on_time": 0
  },
  {
    "task_id":1,
    "duration": 5,
    "priority": "MEDIUM",
    "subtasks": 5,
    "deadline_days": 6,
    "created_to_deadline": 8,
    "user_past_completion": 0.95,
    "task_type": "feature",
    "description_length": 130,
    "comments_count": 0,
    "assigned_team_size": 2,
    "user_availability": 53,
    "no_curr_asigned_tasks": 1,
    "tasks_completed": 14,
    "overdue_tasks": 1,
    "avg_completion_time": 0.55,
    "completed_on_time": 0
  },
  {
    "task_id":1,
    "duration": 5,
    "priority": "LOW",
    "subtasks": 1,
    "deadline_days": 30,
    "created_to_deadline": 30,
    "user_past_completion": 0.96,
    "task_type": "bug",
    "description_length": 76,
    "comments_count": 0,
    "assigned_team_size": 3,
    "user_availability": 66,
    "no_curr_asigned_tasks": 2,
    "tasks_completed": 38,
    "overdue_tasks": 3,
    "avg_completion_time": 0.1,
    "completed_on_time": 1
  },
  {
    "task_id":1,
    "duration": 7,
    "priority": "MEDIUM",
    "subtasks": 1,
    "deadline_days": 5,
    "created_to_deadline": 10,
    "user_past_completion": 0.97,
    "task_type": "bug",
    "description_length": 63,
    "comments_count": 1,
    "assigned_team_size": 2,
    "user_availability": 70,
    "no_curr_asigned_tasks": 5,
    "tasks_completed": 16,
    "overdue_tasks": 3,
    "avg_completion_time": 0.3,
    "completed_on_time": 1
  },
  {
    "task_id":1,
    "duration": 1,
    "priority": "MEDIUM",
    "subtasks": 3,
    "deadline_days": 11,
    "created_to_deadline": 14,
    "user_past_completion": 0.91,
    "task_type": "bug",
    "description_length": 104,
    "comments_count": 2,
    "assigned_team_size": 1,
    "user_availability": 40,
    "no_curr_asigned_tasks": 3,
    "tasks_completed": 24,
    "overdue_tasks": 1,
    "avg_completion_time": 0.14,
    "completed_on_time": 0
  },
  {
    "task_id":1,
    "duration": 1,
    "priority": "MEDIUM",
    "subtasks": 0,
    "deadline_days": 15,
    "created_to_deadline": 15,
    "user_past_completion": 0.72,
    "task_type": "feature",
    "description_length": 177,
    "comments_count": 2,
    "assigned_team_size": 3,
    "user_availability": 96,
    "no_curr_asigned_tasks": 3,
    "tasks_completed": 19,
    "overdue_tasks": 2,
    "avg_completion_time": 0.24,
    "completed_on_time": 1
  },
  {
    "task_id":1,
    "duration": 5,
    "priority": "LOW",
    "subtasks": 1,
    "deadline_days": 16,
    "created_to_deadline": 25,
    "user_past_completion": 0.84,
    "task_type": "documentation",
    "description_length": 92,
    "comments_count": 1,
    "assigned_team_size": 1,
    "user_availability": 49,
    "no_curr_asigned_tasks": 1,
    "tasks_completed": 35,
    "overdue_tasks": 1,
    "avg_completion_time": 0.33,
    "completed_on_time": 0
  },
  {
    "task_id":1,
    "duration": 3,
    "priority": "MEDIUM",
    "subtasks": 0,
    "deadline_days": 28,
    "created_to_deadline": 31,
    "user_past_completion": 0.96,
    "task_type": "feature",
    "description_length": 120,
    "comments_count": 2,
    "assigned_team_size": 3,
    "user_availability": 53,
    "no_curr_asigned_tasks": 5,
    "tasks_completed": 22,
    "overdue_tasks": 2,
    "avg_completion_time": 0.1,
    "completed_on_time": 1
  },
  {
    "task_id":1,
    "duration": 7,
    "priority": "HIGH",
    "subtasks": 2,
    "deadline_days": 22,
    "created_to_deadline": 23,
    "user_past_completion": 0.73,
    "task_type": "bug",
    "description_length": 68,
    "comments_count": 3,
    "assigned_team_size": 1,
    "user_availability": 44,
    "no_curr_asigned_tasks": 5,
    "tasks_completed": 52,
    "overdue_tasks": 5,
    "avg_completion_time": 0.12,
    "completed_on_time": 0
  }

]


###

# Example prediction request
POST http://127.0.0.1:8000/api/v1/tasks/predict
Content-Type: application/json

[
    {
    "task_id": 1,
    "task_type": "feature",
    "priority": "HIGH",
    "duration": 3,
    "subtasks": 0,
    "deadline": "2024-07-02T12:00:00Z",
    "created_at": "2024-06-01T09:00:00Z",
    "description_length": 120,
    "comments_count": 5,
    "assigned_team_size": 9,
    "user_availability": 80,
    "no_curr_asigned_tasks": 1,
    "tasks_completed": 40,
    "overdue_tasks": 0,
    "user_past_completion": 1,
    "avg_completion_time": 0.16
  }
]
